#!/bin/bash

# Install RNAVIEW
wget -qO RNAVIEW.tar.gz "http://ndbserver.rutgers.edu/ndbmodule/services/download/RNAVIEW.tar.gz"
tar -xzvf RNAVIEW.tar.gz
cd RNAVIEW/
make && make clean
cd ~
rm RNAVIEW.tar.gz

# retrieve rnartistcore and build  Kotlin library to describe and plot RNA secondary structures
git clone https://github.com/fjossinet/RNArtistCore.git
cd RNArtistCore/
git pull
mvn clean package
