#!/bin/bash

# set environmental variable
export RNAVIEW="$HOME/RNAVIEW"
export PATH=$RNAVIEW/bin:$PATH

# this must be last line according to
# https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"